# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab403ff6f61672ab270171239355bb525a31fc51f1f06294260ba699d9e6867aff9ba31afb5859f503edb0081934b735c06223588f8388d1aa743fa9718fc75a

test:
  secret_key_base: 0eed0e7546f40f69d241dd9ae28cfbaf01582ac3e1f4d422de12bed0d8fbe32d6e38bb5948879ecd6cf913da81f0527836e8caa9d1239dd0c93057e801020183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
